spring:
  mvc:
    static-path-pattern: /static/**
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
#    key-store-password: 123456
pay:
  unknown: https://lunarclient.top/donate
  wechat:
  qq:
  alipay:
api:
  redirectLaunch: https://api.lunarclientprod.com/launcher/launch
  error: "{\"success\": false, \"error\":  {\"short\":  \"%title%\", \"message\":  \"%msg%\", \"code\": \"%code%\"}}"
