# Fake LunarAPI config
# https://github.com/CubeWhyMC/website

### Spring config ###
spring:
  mvc:
    static-path-pattern: /static/**
  security:
    jwt:
      key: abc-def
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
### Pay redirect Config ###
pay:
  unknown: https://lunarclient.top/donate
  wechat:
  qq:
  alipay:
### API config ###
api:
  version: https://api.github.com/repos/CubeWhyMC/LunarClient-CN/releases
  skin: https://sessionserver.mojang.com/session/minecraft/profile/
  viewCrashReport: https://www.lunarclient.top/crash
  error: "{\"success\": false, \"error\":  {\"short\":  \"%title%\", \"message\":  \"%msg%\", \"code\": \"%code%\"}}"
